// <auto-generated />
namespace Stud_rec.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Level : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Level));
        
        string IMigrationMetadata.Id
        {
            get { return "201507091349418_Level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
